/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador;

import javax.swing.JPanel;

/**
 *
 * @author alberto
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MenuInicio = new javax.swing.JPanel();
        Criar = new javax.swing.JButton();
        Escolher = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CriarTopico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TopicoDefinido = new javax.swing.JPanel();
        eletronica = new javax.swing.JRadioButton();
        desenvolvedor = new javax.swing.JRadioButton();
        readyDefinido = new javax.swing.JButton();
        Ranking = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Aptidão");

        MainPanel.setLayout(new java.awt.CardLayout());

        Criar.setText("Criar");
        Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarActionPerformed(evt);
            }
        });

        Escolher.setText("Escolher");
        Escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolherActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(250, 21, 252));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("              SEJA BEM VINDO AO SISTEMA DE\n       COEFICIENTE DE REDIMENTO ACADÊMICO\n              POR ÁREA DE CONHECIMENTO\n        CLIQUE CRIAR PARA FAZER O SEU TÓPICO\n  OU ESCOLHER PARA SELECIONAR UM ESPECÍFICO\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout MenuInicioLayout = new javax.swing.GroupLayout(MenuInicio);
        MenuInicio.setLayout(MenuInicioLayout);
        MenuInicioLayout.setHorizontalGroup(
            MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInicioLayout.createSequentialGroup()
                .addGroup(MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuInicioLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(Escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuInicioLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        MenuInicioLayout.setVerticalGroup(
            MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInicioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Criar)
                    .addComponent(Escolher))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        MainPanel.add(MenuInicio, "card7");

        jLabel1.setText("Criar Tópico");

        javax.swing.GroupLayout CriarTopicoLayout = new javax.swing.GroupLayout(CriarTopico);
        CriarTopico.setLayout(CriarTopicoLayout);
        CriarTopicoLayout.setHorizontalGroup(
            CriarTopicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarTopicoLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        CriarTopicoLayout.setVerticalGroup(
            CriarTopicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarTopicoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        MainPanel.add(CriarTopico, "card2");

        eletronica.setText("Eletrônica");
        eletronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletronicaActionPerformed(evt);
            }
        });

        desenvolvedor.setText("Desenvolvimento de Software");
        desenvolvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenvolvedorActionPerformed(evt);
            }
        });

        readyDefinido.setText("Ready");
        readyDefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyDefinidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopicoDefinidoLayout = new javax.swing.GroupLayout(TopicoDefinido);
        TopicoDefinido.setLayout(TopicoDefinidoLayout);
        TopicoDefinidoLayout.setHorizontalGroup(
            TopicoDefinidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopicoDefinidoLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(TopicoDefinidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopicoDefinidoLayout.createSequentialGroup()
                        .addComponent(desenvolvedor)
                        .addGap(122, 331, Short.MAX_VALUE))
                    .addGroup(TopicoDefinidoLayout.createSequentialGroup()
                        .addComponent(eletronica)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(TopicoDefinidoLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(readyDefinido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TopicoDefinidoLayout.setVerticalGroup(
            TopicoDefinidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopicoDefinidoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(eletronica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desenvolvedor)
                .addGap(30, 30, 30)
                .addComponent(readyDefinido)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        MainPanel.add(TopicoDefinido, "card3");

        Ranking.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                RankingInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel3.setText("Testando 3");

        javax.swing.GroupLayout RankingLayout = new javax.swing.GroupLayout(Ranking);
        Ranking.setLayout(RankingLayout);
        RankingLayout.setHorizontalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RankingLayout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );
        RankingLayout.setVerticalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        MainPanel.add(Ranking, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarActionPerformed
        // TODO add your handling code here:
        MenuInicio.setVisible(false);
        CriarTopico.setVisible(true);
    }//GEN-LAST:event_CriarActionPerformed

    private void EscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolherActionPerformed
        // TODO add your handling code here:
        MenuInicio.setVisible(false);
        TopicoDefinido.setVisible(true);
    }//GEN-LAST:event_EscolherActionPerformed

    private void desenvolvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenvolvedorActionPerformed
        // TODO add your handling code here:
        eletronica.setSelected(false);
     
    }//GEN-LAST:event_desenvolvedorActionPerformed

    private void eletronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletronicaActionPerformed
        // TODO add your handling code here:
        desenvolvedor.setSelected(false);
        
    }//GEN-LAST:event_eletronicaActionPerformed

    private void readyDefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyDefinidoActionPerformed
        // TODO add your handling code here:
        TopicoDefinido.setVisible(false);
        Ranking.setVisible(true);
    }//GEN-LAST:event_readyDefinidoActionPerformed

    private void RankingInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_RankingInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_RankingInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ExtrairDados dados = new ExtrairDados();
				
        dados.criaAlunos("Alfredo");
	dados.criaAlunos("Leonardo");
	dados.criaAlunos("Daniel");
        dados.criaAlunos("Alberto");
	dados.criaAlunos("Willian");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Criar;
    private javax.swing.JPanel CriarTopico;
    private javax.swing.JButton Escolher;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuInicio;
    private javax.swing.JPanel Ranking;
    private javax.swing.JPanel TopicoDefinido;
    private javax.swing.JRadioButton desenvolvedor;
    private javax.swing.JRadioButton eletronica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton readyDefinido;
    // End of variables declaration//GEN-END:variables
}
